// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: pageinflation/query.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/gogo/protobuf/gogoproto"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// QueryParamsRequest is request type for the Query/Params RPC method.
type QueryParamsRequest struct {
}

func (m *QueryParamsRequest) Reset()         { *m = QueryParamsRequest{} }
func (m *QueryParamsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryParamsRequest) ProtoMessage()    {}
func (*QueryParamsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9d409b4ff2e9334, []int{0}
}
func (m *QueryParamsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsRequest.Merge(m, src)
}
func (m *QueryParamsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsRequest proto.InternalMessageInfo

// QueryParamsResponse is response type for the Query/Params RPC method.
type QueryParamsResponse struct {
	// params holds all the parameters of this module.
	Params Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
}

func (m *QueryParamsResponse) Reset()         { *m = QueryParamsResponse{} }
func (m *QueryParamsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryParamsResponse) ProtoMessage()    {}
func (*QueryParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9d409b4ff2e9334, []int{1}
}
func (m *QueryParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsResponse.Merge(m, src)
}
func (m *QueryParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsResponse proto.InternalMessageInfo

func (m *QueryParamsResponse) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

type QueryGetMintDenomRequest struct {
}

func (m *QueryGetMintDenomRequest) Reset()         { *m = QueryGetMintDenomRequest{} }
func (m *QueryGetMintDenomRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetMintDenomRequest) ProtoMessage()    {}
func (*QueryGetMintDenomRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9d409b4ff2e9334, []int{2}
}
func (m *QueryGetMintDenomRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetMintDenomRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetMintDenomRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetMintDenomRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetMintDenomRequest.Merge(m, src)
}
func (m *QueryGetMintDenomRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetMintDenomRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetMintDenomRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetMintDenomRequest proto.InternalMessageInfo

type QueryGetMintDenomResponse struct {
	MintDenom MintDenom `protobuf:"bytes,1,opt,name=MintDenom,proto3" json:"MintDenom"`
}

func (m *QueryGetMintDenomResponse) Reset()         { *m = QueryGetMintDenomResponse{} }
func (m *QueryGetMintDenomResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetMintDenomResponse) ProtoMessage()    {}
func (*QueryGetMintDenomResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9d409b4ff2e9334, []int{3}
}
func (m *QueryGetMintDenomResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetMintDenomResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetMintDenomResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetMintDenomResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetMintDenomResponse.Merge(m, src)
}
func (m *QueryGetMintDenomResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetMintDenomResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetMintDenomResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetMintDenomResponse proto.InternalMessageInfo

func (m *QueryGetMintDenomResponse) GetMintDenom() MintDenom {
	if m != nil {
		return m.MintDenom
	}
	return MintDenom{}
}

type QueryGetStartBlockRequest struct {
}

func (m *QueryGetStartBlockRequest) Reset()         { *m = QueryGetStartBlockRequest{} }
func (m *QueryGetStartBlockRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetStartBlockRequest) ProtoMessage()    {}
func (*QueryGetStartBlockRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9d409b4ff2e9334, []int{4}
}
func (m *QueryGetStartBlockRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetStartBlockRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetStartBlockRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetStartBlockRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetStartBlockRequest.Merge(m, src)
}
func (m *QueryGetStartBlockRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetStartBlockRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetStartBlockRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetStartBlockRequest proto.InternalMessageInfo

type QueryGetStartBlockResponse struct {
	StartBlock StartBlock `protobuf:"bytes,1,opt,name=StartBlock,proto3" json:"StartBlock"`
}

func (m *QueryGetStartBlockResponse) Reset()         { *m = QueryGetStartBlockResponse{} }
func (m *QueryGetStartBlockResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetStartBlockResponse) ProtoMessage()    {}
func (*QueryGetStartBlockResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9d409b4ff2e9334, []int{5}
}
func (m *QueryGetStartBlockResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetStartBlockResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetStartBlockResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetStartBlockResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetStartBlockResponse.Merge(m, src)
}
func (m *QueryGetStartBlockResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetStartBlockResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetStartBlockResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetStartBlockResponse proto.InternalMessageInfo

func (m *QueryGetStartBlockResponse) GetStartBlock() StartBlock {
	if m != nil {
		return m.StartBlock
	}
	return StartBlock{}
}

type QueryGetMintedPoolRequest struct {
}

func (m *QueryGetMintedPoolRequest) Reset()         { *m = QueryGetMintedPoolRequest{} }
func (m *QueryGetMintedPoolRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetMintedPoolRequest) ProtoMessage()    {}
func (*QueryGetMintedPoolRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9d409b4ff2e9334, []int{6}
}
func (m *QueryGetMintedPoolRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetMintedPoolRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetMintedPoolRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetMintedPoolRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetMintedPoolRequest.Merge(m, src)
}
func (m *QueryGetMintedPoolRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetMintedPoolRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetMintedPoolRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetMintedPoolRequest proto.InternalMessageInfo

type QueryGetMintedPoolResponse struct {
	MintedPool MintedPool `protobuf:"bytes,1,opt,name=MintedPool,proto3" json:"MintedPool"`
}

func (m *QueryGetMintedPoolResponse) Reset()         { *m = QueryGetMintedPoolResponse{} }
func (m *QueryGetMintedPoolResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetMintedPoolResponse) ProtoMessage()    {}
func (*QueryGetMintedPoolResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9d409b4ff2e9334, []int{7}
}
func (m *QueryGetMintedPoolResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetMintedPoolResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetMintedPoolResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetMintedPoolResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetMintedPoolResponse.Merge(m, src)
}
func (m *QueryGetMintedPoolResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetMintedPoolResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetMintedPoolResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetMintedPoolResponse proto.InternalMessageInfo

func (m *QueryGetMintedPoolResponse) GetMintedPool() MintedPool {
	if m != nil {
		return m.MintedPool
	}
	return MintedPool{}
}

func init() {
	proto.RegisterType((*QueryParamsRequest)(nil), "smartdev0328.bluechip.pageinflation.QueryParamsRequest")
	proto.RegisterType((*QueryParamsResponse)(nil), "smartdev0328.bluechip.pageinflation.QueryParamsResponse")
	proto.RegisterType((*QueryGetMintDenomRequest)(nil), "smartdev0328.bluechip.pageinflation.QueryGetMintDenomRequest")
	proto.RegisterType((*QueryGetMintDenomResponse)(nil), "smartdev0328.bluechip.pageinflation.QueryGetMintDenomResponse")
	proto.RegisterType((*QueryGetStartBlockRequest)(nil), "smartdev0328.bluechip.pageinflation.QueryGetStartBlockRequest")
	proto.RegisterType((*QueryGetStartBlockResponse)(nil), "smartdev0328.bluechip.pageinflation.QueryGetStartBlockResponse")
	proto.RegisterType((*QueryGetMintedPoolRequest)(nil), "smartdev0328.bluechip.pageinflation.QueryGetMintedPoolRequest")
	proto.RegisterType((*QueryGetMintedPoolResponse)(nil), "smartdev0328.bluechip.pageinflation.QueryGetMintedPoolResponse")
}

func init() { proto.RegisterFile("pageinflation/query.proto", fileDescriptor_f9d409b4ff2e9334) }

var fileDescriptor_f9d409b4ff2e9334 = []byte{
	// 533 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x94, 0x4f, 0x6f, 0xd3, 0x30,
	0x18, 0xc6, 0x1b, 0x04, 0x95, 0x30, 0x37, 0xb3, 0xc3, 0x16, 0x50, 0x86, 0xca, 0x05, 0x31, 0x11,
	0xaf, 0xad, 0xc4, 0x7a, 0x01, 0xa4, 0x0a, 0x09, 0x71, 0x98, 0x54, 0x8a, 0xb8, 0x70, 0x29, 0x4e,
	0x6b, 0xb2, 0x88, 0xc4, 0xaf, 0x17, 0xbb, 0x13, 0xbb, 0xf2, 0x09, 0x90, 0xe0, 0x83, 0xf0, 0x1d,
	0x38, 0xb0, 0xe3, 0x24, 0x2e, 0x9c, 0x10, 0x6a, 0xf9, 0x20, 0x28, 0x8e, 0x33, 0x27, 0x34, 0x93,
	0x92, 0xdd, 0xa2, 0xf7, 0xcf, 0xf3, 0xfe, 0x1e, 0xe7, 0xb5, 0xd1, 0x8e, 0xa0, 0x21, 0x8b, 0xf8,
	0xfb, 0x98, 0xaa, 0x08, 0x38, 0x39, 0x5e, 0xb2, 0xf4, 0xd4, 0x17, 0x29, 0x28, 0xc0, 0xf7, 0x65,
	0x42, 0x53, 0xb5, 0x60, 0x27, 0xfb, 0xc3, 0xc1, 0xc8, 0x0f, 0xe2, 0x25, 0x9b, 0x1f, 0x45, 0xc2,
	0xaf, 0x34, 0xb8, 0x5b, 0x21, 0x84, 0xa0, 0xeb, 0x49, 0xf6, 0x95, 0xb7, 0xba, 0x77, 0x43, 0x80,
	0x30, 0x66, 0x84, 0x8a, 0x88, 0x50, 0xce, 0x41, 0xe9, 0x62, 0x69, 0xb2, 0x0f, 0xe7, 0x20, 0x13,
	0x90, 0x24, 0xa0, 0x92, 0xe5, 0x13, 0xc9, 0x49, 0x3f, 0x60, 0x8a, 0xf6, 0x89, 0xa0, 0x61, 0xc4,
	0x75, 0xb1, 0xa9, 0x75, 0xab, 0x7c, 0x82, 0xa6, 0x34, 0x29, 0x74, 0xbc, 0x6a, 0x2e, 0x89, 0xb8,
	0x9a, 0x2d, 0x18, 0x87, 0xc4, 0xe4, 0x77, 0xab, 0x79, 0xa9, 0x68, 0xaa, 0x66, 0x41, 0x0c, 0xf3,
	0x0f, 0xf5, 0x05, 0x99, 0x00, 0x5b, 0xcc, 0x04, 0x40, 0x9c, 0x17, 0xf4, 0xb6, 0x10, 0x7e, 0x95,
	0xf1, 0x4d, 0xf4, 0xd8, 0x29, 0x3b, 0x5e, 0x32, 0xa9, 0x7a, 0xef, 0xd0, 0xed, 0x4a, 0x54, 0x0a,
	0xe0, 0x92, 0xe1, 0x97, 0xa8, 0x9b, 0xe3, 0x6d, 0x3b, 0xf7, 0x9c, 0x07, 0xb7, 0x06, 0x7b, 0x7e,
	0x83, 0x03, 0xf4, 0x73, 0x91, 0xf1, 0xf5, 0xb3, 0xdf, 0xbb, 0x9d, 0xa9, 0x11, 0xe8, 0xb9, 0x68,
	0x5b, 0x4f, 0x78, 0xc1, 0xd4, 0x61, 0xc4, 0xd5, 0xf3, 0xcc, 0x54, 0x31, 0x1d, 0xd0, 0x4e, 0x4d,
	0xce, 0x30, 0x4c, 0xd1, 0xcd, 0x8b, 0xa0, 0xc1, 0xf0, 0x1b, 0x61, 0x5c, 0x74, 0x19, 0x12, 0x2b,
	0xd3, 0xbb, 0x63, 0x07, 0xbe, 0xce, 0x8e, 0x70, 0x9c, 0x9d, 0x60, 0x41, 0x23, 0x91, 0x5b, 0x97,
	0x34, 0x38, 0x6f, 0x10, 0xb2, 0x51, 0xc3, 0x43, 0x1a, 0xf1, 0xd8, 0x36, 0x03, 0x54, 0x12, 0x2a,
	0x13, 0x1d, 0xea, 0x7f, 0x36, 0x01, 0x88, 0x6b, 0x88, 0xca, 0x49, 0x4b, 0x64, 0xa3, 0xad, 0x88,
	0x6c, 0x5b, 0x41, 0x64, 0x23, 0x83, 0xaf, 0x5d, 0x74, 0x43, 0x4f, 0xc5, 0xdf, 0x1c, 0xd4, 0xcd,
	0xff, 0x29, 0x3e, 0x68, 0xa4, 0xbb, 0xb9, 0x60, 0xee, 0xa8, 0x7d, 0x63, 0x6e, 0xaf, 0x37, 0xfc,
	0xf4, 0xf3, 0xef, 0x97, 0x6b, 0x8f, 0xf0, 0x1e, 0x29, 0x2b, 0x90, 0x42, 0x81, 0xd4, 0xdd, 0x26,
	0xfc, 0xdd, 0x29, 0x6d, 0x0d, 0x7e, 0xd2, 0x7c, 0x78, 0xcd, 0x7a, 0xba, 0x4f, 0xaf, 0xda, 0x6e,
	0x1c, 0x1c, 0x68, 0x07, 0x7d, 0x4c, 0x1a, 0x39, 0xb0, 0x77, 0x1e, 0xff, 0x70, 0xca, 0xcb, 0x86,
	0xdb, 0x71, 0x6c, 0x2c, 0xb6, 0xfb, 0xec, 0xca, 0xfd, 0xc6, 0xc8, 0x48, 0x1b, 0x19, 0xe0, 0xfd,
	0x46, 0x46, 0x4a, 0x8f, 0x93, 0x76, 0x62, 0x77, 0x0b, 0xb7, 0x3f, 0xd1, 0xca, 0x85, 0x68, 0xe9,
	0x64, 0xf3, 0xce, 0xb4, 0x74, 0x52, 0x7a, 0x45, 0xc7, 0x93, 0xb3, 0x95, 0xe7, 0x9c, 0xaf, 0x3c,
	0xe7, 0xcf, 0xca, 0x73, 0x3e, 0xaf, 0xbd, 0xce, 0xf9, 0xda, 0xeb, 0xfc, 0x5a, 0x7b, 0x9d, 0xb7,
	0x8f, 0xc3, 0x48, 0x1d, 0x2d, 0x03, 0x7f, 0x0e, 0xc9, 0x25, 0xaa, 0x1f, 0xff, 0xd3, 0x55, 0xa7,
	0x82, 0xc9, 0xa0, 0xab, 0x1f, 0xe6, 0xe1, 0xbf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x20, 0x0a, 0x39,
	0x92, 0xb8, 0x06, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Parameters queries the parameters of the module.
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	// Queries a MintDenom by index.
	MintDenom(ctx context.Context, in *QueryGetMintDenomRequest, opts ...grpc.CallOption) (*QueryGetMintDenomResponse, error)
	// Queries a StartBlock by index.
	StartBlock(ctx context.Context, in *QueryGetStartBlockRequest, opts ...grpc.CallOption) (*QueryGetStartBlockResponse, error)
	// Queries a MintedPool by index.
	MintedPool(ctx context.Context, in *QueryGetMintedPoolRequest, opts ...grpc.CallOption) (*QueryGetMintedPoolResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, "/smartdev0328.bluechip.pageinflation.Query/Params", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) MintDenom(ctx context.Context, in *QueryGetMintDenomRequest, opts ...grpc.CallOption) (*QueryGetMintDenomResponse, error) {
	out := new(QueryGetMintDenomResponse)
	err := c.cc.Invoke(ctx, "/smartdev0328.bluechip.pageinflation.Query/MintDenom", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) StartBlock(ctx context.Context, in *QueryGetStartBlockRequest, opts ...grpc.CallOption) (*QueryGetStartBlockResponse, error) {
	out := new(QueryGetStartBlockResponse)
	err := c.cc.Invoke(ctx, "/smartdev0328.bluechip.pageinflation.Query/StartBlock", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) MintedPool(ctx context.Context, in *QueryGetMintedPoolRequest, opts ...grpc.CallOption) (*QueryGetMintedPoolResponse, error) {
	out := new(QueryGetMintedPoolResponse)
	err := c.cc.Invoke(ctx, "/smartdev0328.bluechip.pageinflation.Query/MintedPool", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Parameters queries the parameters of the module.
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	// Queries a MintDenom by index.
	MintDenom(context.Context, *QueryGetMintDenomRequest) (*QueryGetMintDenomResponse, error)
	// Queries a StartBlock by index.
	StartBlock(context.Context, *QueryGetStartBlockRequest) (*QueryGetStartBlockResponse, error)
	// Queries a MintedPool by index.
	MintedPool(context.Context, *QueryGetMintedPoolRequest) (*QueryGetMintedPoolResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Params(ctx context.Context, req *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}
func (*UnimplementedQueryServer) MintDenom(ctx context.Context, req *QueryGetMintDenomRequest) (*QueryGetMintDenomResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MintDenom not implemented")
}
func (*UnimplementedQueryServer) StartBlock(ctx context.Context, req *QueryGetStartBlockRequest) (*QueryGetStartBlockResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartBlock not implemented")
}
func (*UnimplementedQueryServer) MintedPool(ctx context.Context, req *QueryGetMintedPoolRequest) (*QueryGetMintedPoolResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MintedPool not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/smartdev0328.bluechip.pageinflation.Query/Params",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_MintDenom_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetMintDenomRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).MintDenom(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/smartdev0328.bluechip.pageinflation.Query/MintDenom",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).MintDenom(ctx, req.(*QueryGetMintDenomRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_StartBlock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetStartBlockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).StartBlock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/smartdev0328.bluechip.pageinflation.Query/StartBlock",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).StartBlock(ctx, req.(*QueryGetStartBlockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_MintedPool_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetMintedPoolRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).MintedPool(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/smartdev0328.bluechip.pageinflation.Query/MintedPool",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).MintedPool(ctx, req.(*QueryGetMintedPoolRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "smartdev0328.bluechip.pageinflation.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
		{
			MethodName: "MintDenom",
			Handler:    _Query_MintDenom_Handler,
		},
		{
			MethodName: "StartBlock",
			Handler:    _Query_StartBlock_Handler,
		},
		{
			MethodName: "MintedPool",
			Handler:    _Query_MintedPool_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pageinflation/query.proto",
}

func (m *QueryParamsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryGetMintDenomRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetMintDenomRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetMintDenomRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryGetMintDenomResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetMintDenomResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetMintDenomResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.MintDenom.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryGetStartBlockRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetStartBlockRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetStartBlockRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryGetStartBlockResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetStartBlockResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetStartBlockResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.StartBlock.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryGetMintedPoolRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetMintedPoolRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetMintedPoolRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryGetMintedPoolResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetMintedPoolResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetMintedPoolResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.MintedPool.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryParamsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryGetMintDenomRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryGetMintDenomResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.MintDenom.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryGetStartBlockRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryGetStartBlockResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.StartBlock.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryGetMintedPoolRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryGetMintedPoolResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.MintedPool.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryParamsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetMintDenomRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetMintDenomRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetMintDenomRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetMintDenomResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetMintDenomResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetMintDenomResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MintDenom", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.MintDenom.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetStartBlockRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetStartBlockRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetStartBlockRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetStartBlockResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetStartBlockResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetStartBlockResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field StartBlock", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.StartBlock.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetMintedPoolRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetMintedPoolRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetMintedPoolRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetMintedPoolResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetMintedPoolResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetMintedPoolResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MintedPool", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.MintedPool.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
